### ISSUE TITLE
Protocol 'ExpectedCount' cannot be nested inside another declaration

### ISSUE THREAD

**Issue by andrzejplatek** [pointfreeco/swift-issue-reporting#118]
When updating the package to version 1.2.4 we were unable to build a package. I could reproduce the issue by adding a package to new empty project.

Swift 5.9
Xcode version: 15.2

![Zrzut ekranu 2024-08-20 o 10 09 36](https://github.com/user-attachments/assets/d3c471ae-f77d-44cc-89f0-a5427a3960b4)

**Comment by MartinMetselaar** [comment]
Nested protocols have been introduced since Swift `5.10`:
https://github.com/swiftlang/swift-evolution/blob/main/proposals/0404-nested-protocols.md

So you can start using the latest swift version to resolve the issue. I don't know what the guidelines are for this project to support older swift versions but I was encountering the same issue.

**Comment by andrzejplatek** [comment]
I guess Swift.package should be updated to `swift-tools-version: 5.10` in that case

**Comment by mbrandonw** [comment]
Hi @andrzejplatek, thanks for the report! That was a mistake on our part. We seem to have lost Swift 5.9 CI and so it did not let us know of the problem. Hopefully this #119 will fix things and we can make a new release soon.
